package com.example.retinavision.agent;

public enum AgentSkillCode {
    DOCTOR_WORKLOAD_OVERVIEW,
    ASSIGNED_CASE_SEARCH,
    CASE_CLINICAL_SUMMARY,
    CASE_FOLLOWUP_ANALYSIS,
    DOCTOR_TASK_SEARCH,
    DOCTOR_CLINICAL_QUEUE,
    MEDICAL_KNOWLEDGE_QA,
    MY_CASE_LIST,
    MY_CASE_PROGRESS,
    MY_SIGNED_REPORT,
    PATIENT_KNOWLEDGE_QA
}
