package com.example.retinavision.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.example.retinavision.constant.ErrorMessageSignal;
import com.example.retinavision.enumeration.*;
import com.example.retinavision.exception.BaseException;
import com.example.retinavision.exception.ConflictException;
import com.example.retinavision.mapper.*;
import com.example.retinavision.pojo.DTO.UpdateReportDraftDTO;
import com.example.retinavision.pojo.Entity.*;
import com.example.retinavision.service.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.transaction.annotation.Transactional;
import java.io.IOException;
import java.nio.file.*;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.util.*;

@Service public class AnalysisReportServiceImpl implements AnalysisReportService {
 private final AnalysisResultMapper results;private final AnalysisReportMapper reports;private final AnalysisReviewMapper reviews;private final UserRegisterMapper users;private final ReportPdfRenderer renderer;private final Path root;private final Path imageRoot;private final TaskMapper tasks;private final CaseMapper cases;private final ImageMapper images;private final AnalysisCorrectionMapper corrections;private final ObjectMapper json=new ObjectMapper();
 @Autowired public AnalysisReportServiceImpl(AnalysisResultMapper a,AnalysisReportMapper b,AnalysisReviewMapper c,UserRegisterMapper d,ReportPdfRenderer e,TaskMapper tasks,CaseMapper cases,ImageMapper images,AnalysisCorrectionMapper corrections,@Value("${retina.upload.result-root:uploads/results}")String root,@Value("${retina.upload.image-root:uploads/images}")String imageRoot){results=a;reports=b;reviews=c;users=d;renderer=e;this.tasks=tasks;this.cases=cases;this.images=images;this.corrections=corrections;this.root=Paths.get(root).toAbsolutePath().normalize();this.imageRoot=Paths.get(imageRoot).toAbsolutePath().normalize();}
 public AnalysisReportServiceImpl(AnalysisResultMapper a,AnalysisReportMapper b,AnalysisReviewMapper c,UserRegisterMapper d,ReportPdfRenderer e,String root){this(a,b,c,d,e,null,null,null,null,root,"uploads/images");}
 @Override @Transactional public AnalysisReportEntity getOrCreateDraft(Long id,Integer uid){AnalysisResultEntity result=requireResult(id);return list(id).stream().filter(x->x.getStatus()==ReportStatus.DRAFT).reduce((a,b)->b).orElseGet(()->{AnalysisReportEntity x=new AnalysisReportEntity();LocalDateTime n=LocalDateTime.now();x.setResultId(id);x.setVersion(next(id));x.setStatus(ReportStatus.DRAFT);x.setDraftJson(defaultDraft(result));x.setCreatedBy(uid);x.setCreatedAt(n);x.setUpdatedAt(n);reports.insert(x);return x;});}
 @Override @Transactional public AnalysisReportEntity updateDraft(Long id,UpdateReportDraftDTO q,Integer uid){AnalysisReportEntity x=getOrCreateDraft(id,uid);if(x.getStatus()!=ReportStatus.DRAFT)throw conflict("已签发报告不可修改");try{json.readTree(q.getDraftJson());}catch(Exception e){throw new BaseException(ErrorMessageSignal.PARAM_ERROR,"报告草稿必须是合法 JSON");}if(q.getCorrectionVersion()!=null){AnalysisCorrectionEntity c=corrections.selectOne(new LambdaQueryWrapper<AnalysisCorrectionEntity>().eq(AnalysisCorrectionEntity::getResultId,id).eq(AnalysisCorrectionEntity::getVersion,q.getCorrectionVersion()));if(c==null||c.getStatus()!=CorrectionStatus.ACCEPTED)throw conflict("报告只能采用医生审核接受的修正版本");}x.setCorrectionVersion(q.getCorrectionVersion());x.setDraftJson(q.getDraftJson());x.setUpdatedAt(LocalDateTime.now());reports.updateById(x);return x;}
 @Override @Transactional public AnalysisReportEntity sign(Long id,Integer doctorId){AnalysisReviewEntity review=reviews.selectOne(new LambdaQueryWrapper<AnalysisReviewEntity>().eq(AnalysisReviewEntity::getResultId,id));if(review==null||review.getStatus()!=ReviewStatus.APPROVED)throw conflict("只有审核通过的结果才能签发报告");UserEntity doctor=users.selectById(doctorId);if(doctor==null||doctor.getProfessionalNo()==null)throw new BaseException(ErrorMessageSignal.FORBIDDEN,"缺少可信医生身份");AnalysisReportEntity x=getOrCreateDraft(id,doctorId);String key="reports/"+id+"/v"+x.getVersion()+".pdf";Path finalPath=resolve(key),temp=resolve(key+".tmp");try{renderer.render(document(requireResult(id),x),temp);String hash=hex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(temp)));Files.createDirectories(finalPath.getParent());Files.move(temp,finalPath,StandardCopyOption.REPLACE_EXISTING);LocalDateTime n=LocalDateTime.now();for(AnalysisReportEntity old:list(id)){if(old.getStatus()==ReportStatus.SIGNED){old.setStatus(ReportStatus.SUPERSEDED);old.setUpdatedAt(n);reports.updateById(old);}}x.setStatus(ReportStatus.SIGNED);x.setReportObjectKey(key);x.setReportSha256(hash);x.setSignedBy(doctorId);x.setSignerNameSnapshot(doctor.getRealName());x.setProfessionalNoSnapshot(doctor.getProfessionalNo());x.setSignedAt(n);x.setUpdatedAt(n);if(reports.updateById(x)!=1)throw new IllegalStateException("signed report row was not updated");return x;}catch(BaseException e){cleanup(temp);throw e;}catch(Exception e){cleanup(temp);cleanup(finalPath);throw new BaseException(ErrorMessageSignal.FILE_STORAGE_ERROR,"报告签发失败");}}
 @Override public List<AnalysisReportEntity> list(Long id){requireResult(id);return reports.selectList(new LambdaQueryWrapper<AnalysisReportEntity>().eq(AnalysisReportEntity::getResultId,id).orderByAsc(AnalysisReportEntity::getVersion));}
 @Override public AnalysisReportEntity get(Long id,Integer version){return list(id).stream().filter(x->x.getVersion().equals(version)).findFirst().orElseThrow(()->new BaseException(ErrorMessageSignal.NOT_FOUND,"报告版本不存在"));}
 @Override public Path getFile(Long id,Integer version){AnalysisReportEntity x=get(id,version);if(x.getStatus()!=ReportStatus.SIGNED&&x.getStatus()!=ReportStatus.SUPERSEDED)throw conflict("报告尚未签发");Path p=resolve(x.getReportObjectKey());if(!Files.isRegularFile(p))throw new BaseException(ErrorMessageSignal.NOT_FOUND,"报告文件不存在");return p;}
 private AnalysisResultEntity requireResult(Long id){AnalysisResultEntity r=results.selectById(id);if(r==null)throw new BaseException(ErrorMessageSignal.NOT_FOUND,"分析结果不存在");return r;}private int next(Long id){return list(id).stream().mapToInt(AnalysisReportEntity::getVersion).max().orElse(0)+1;}private Path resolve(String k){Path p=root.resolve(k).normalize();if(!p.startsWith(root))throw new BaseException(ErrorMessageSignal.PARAM_ERROR,"报告路径无效");return p;}private BaseException conflict(String s){return new ConflictException(s);}private void cleanup(Path p){try{Files.deleteIfExists(p);}catch(IOException ignored){}}private String hex(byte[] x){return java.util.HexFormat.of().formatHex(x);}
 private String defaultDraft(AnalysisResultEntity r){Map<String,Object> m=new LinkedHashMap<>();m.put("resultId",r.getId());m.put("resultType",r.getResultType());m.put("aiResult",r.getResultJson());m.put("modelName",r.getModelName());m.put("modelVersion",r.getModelVersion());m.put("processingTimeMs",r.getProcessingTimeMs());m.put("findings","");m.put("conclusion","");m.put("recommendation","");m.put("disclaimer","AI 辅助分析，不等同于独立医学诊断");try{return json.writeValueAsString(m);}catch(Exception e){return "{}";}}
 private ReportPdfDocument document(AnalysisResultEntity r,AnalysisReportEntity report){Path original=null,mask=path(root,r.getMaskObjectKey()),corrected=null;StringBuilder content=new StringBuilder(report.getDraftJson());if(tasks!=null){TaskEntity t=tasks.selectById(r.getTaskId());if(t!=null){CaseEntity c=cases.selectById(t.getCaseId());ImageFileEntity i=images.selectById(t.getImageFileId());if(c!=null)content.append(" 病例号:").append(c.getCaseNo()).append(" 患者编码:").append(c.getPatientCode()).append(" 眼别:").append(c.getEyeSide());if(i!=null){content.append(" 图像质量:").append(i.getQualityStatus()).append(" 评分:").append(i.getQualityScore());original=path(imageRoot,i.getStorageObjectKey());}}}if(report.getCorrectionVersion()!=null&&corrections!=null){AnalysisCorrectionEntity c=corrections.selectOne(new LambdaQueryWrapper<AnalysisCorrectionEntity>().eq(AnalysisCorrectionEntity::getResultId,r.getId()).eq(AnalysisCorrectionEntity::getVersion,report.getCorrectionVersion()));if(c!=null){corrected=path(root,c.getCorrectedMaskObjectKey());content.append(" 修正版本:").append(c.getVersion());}}return new ReportPdfDocument(content.toString(),original,mask,corrected);}
 private Path path(Path base,String key){if(key==null)return null;Path p=base.resolve(key).normalize();return p.startsWith(base)?p:null;}
}
