server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: retina-vision-backend

  profiles:
    active: dev


retina:
  jwt:
    secret: retina-vision-dev-secret-retina-vision-dev-secret
    expire-hours: 24